# PostgreSQL
spring:

  servlet:
    # Subida de archivos   
   multipart: 
    max-file-size: 10MB 
    max-request-size: 10MB
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ImportDS
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      #value="update" o value="create-drop"
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true

server:
  port: 8088
  